#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
char ch;
cout<<endl<<"Enter a char : ";
cin>>ch;
switch(ch)
{
case 'a':
cout<<endl<<"Char is a Vowel.";
break;
case 'A':
cout<<endl<<"Char is a Vowel.";
break;
case 'e':
cout<<endl<<"Char is a Vowel.";
break;
case 'E':
cout<<endl<<"Char is a Vowel.";
break;
case 'i':
cout<<endl<<"Char is a Vowel.";
break;
case 'I':
cout<<endl<<"Char is a Vowel.";
break;
case 'o':
cout<<endl<<"Char is a Vowel.";
break;
case 'O':
cout<<endl<<"Char is a Vowel.";
break;
case 'u':
cout<<endl<<"Char is a Vowel.";
break;
case 'U':
cout<<endl<<"Char is a Vowel.";
break;
default:
cout<<endl<<"Char is a Consonant." ;
}
getch();
}
